name: Generate Space Invaders

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate Space Invaders
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: nagrajhegde834
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-space-invaders.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b86e8,#3066be

      - uses: EndBug/add-and-commit@v9
        with:
          add: dist
          message: "Update Space Invaders animation"
